<!-- Footer -->
</div>
<footer class="page-footer font-small blue pt-4" id="my-footer" style="background-color: <?php echo $secondary;?>">

    <!-- Footer Links -->
    <div class="container-fluid text-center text-md-left" id="my-footer-div">

        <!-- Grid row -->
        <div class="row">

            <!-- Grid column -->
            <div class="col-md-6 mt-md-0 mt-3">

                <!-- Content -->
                <h5 class="text-uppercase"><b><?php echo $name; ?></b></h5>
                <!--<p>Here you can use rows and columns to organize your footer content.</p>-->
                <a href="index2.php"><?php echo $logoFooter; ?></a>


            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none pb-3">

            <!-- Grid column -->
            <div class="col-md-3 mb-md-0 mb-3">

                <!-- Links -->


            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-3 mb-md-0 mb-3">

                <!-- Links -->
                <h5 class="text-uppercase">Links</h5>

                <ul class="list-unstyled">
                    <li>
                        <a href="form.php" style="color: <?php echo $primary;?>">Book an MOT</a>
                    </li>
                    <li>
                        <a href="contact.php" style="color: <?php echo $primary;?>">Contact</a>
                    </li>
                    <li>
                        <a href="login.php" style="color: <?php echo $primary;?>">Login/Register</a>
                    </li>
                    <li>
                        <a href="index2.php" style="color: <?php echo $primary;?>">Index</a>
                    </li>
                </ul>

            </div>
            <!-- Grid column -->

        </div>
        <!-- Grid row -->

        <div class="footer-copyright py-3">Website created using
            <a href="https://www.linkedin.com/in/matthew-fard-772393200/" target="_blank" class="link-3" style="color: <?php echo $primary;?>">Matthew Fard's</a>
            website creation tool
        </div>

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->

    <!-- Copyright -->

</footer>
<!-- Footer -->