<?php require('template/header.phtml') ?>

<body>

<!-- Step 4-->
<section class="page-section" id="colour_picker" style="height: 100vh; max-width: 1000px; margin: auto">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 col-xl-6 text-center">
                <h2 class="mt-0">Thank You for Using Our Website Builder!</h2>
                <hr class="divider" />
                <p class="text-muted mb-5">Below is your unique link to your brand-new website. Click the link for a tour of your site.</p>
            </div>
            <p id="my-navlink2" style="text-align: center; font-size: 150%"><?php echo $url;?></p>
        </div>
    </div>


</section>
</body>

<?php require('template/footer.phtml') ?>
