<?php require('template/header.phtml') ?>

<body>

<!-- Step 3-->
<section id="website-preview" style="padding-top: 13rem; max-width: 1000px; margin: auto">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 col-xl-6 text-center">
                <h2 class="mt-0">Customise Your Site</h2>
                <hr class="divider" />
                <p class="text-muted mb-5">Scroll down to see a preview of your website. Complete each step to fully customise it for your business.</p>
            </div>
        </div>
    </div>

</section>
        <!-- Example Website -->
        <div class="browser-window" style="width: 85%; margin: auto">
            <div class="browser-header">
                <div class="browser-buttons">
                    <div class="browser-button close"></div>
                    <div class="browser-button minimize"></div>
                    <div class="browser-button maximize"></div>
                </div>
                <div class="browser-url">www.garage.com</div>
            </div>
            <div class="browser-content">
                <div id="content3" class="col-xs-6 col-sm-9 col-md-10">

                    <nav class="navbar navbar-expand-lg navbar-light" id="my-navbar">
                        <!-- Link that takes you to index page -->
                        <a class="navbar-brand" id="my-brand" href="#">
                            <!-- Image of logo shown on the left hand side of navbar -->
                            <img src="images/spanner-logo.png" width="50px" height="50px"> <?php echo strtoupper($_SESSION['websiteName']); ?>
                        </a>
                        <!-- button for navbar drop down when on mobile -->
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <!-- All navbar links-->
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ml-auto" id="my-ul">
                                <!-- Home link to index page -->
                                <li class="nav-item" >
                                    <a class="nav-link" id="my-navlink" href="#">Book an MOT<span class="sr-only">(current)</span></a>
                                </li>
                                <!-- Auctions link to auctions page -->
                                <li class="nav-item">
                                    <a class="nav-link" id="my-navlink" href="#">My Bookings</a>
                                </li>
                                <!-- Bidding list link to list page -->
                                <li class="nav-item">
                                    <a class="nav-link" id="my-navlink" href="#" >Contact Us</a>
                                </li>
                                <!-- Login link to login/ logout page -->
                                <li class="nav-item">
                                    <!-- Will echo login on logout depending on if the user is already logged in -->
                                    <a class="nav-link" id="my-navlink-last" href="#">Login</a>
                                </li>
                            </ul>

                        </div>

                    </nav>
                    <div class="row" id="hint-row">
                        <div class="col-sm">
                            <div id="index-left" style="margin-bottom: 50px">
                                <h1 id="my-heading">WELCOME TO <?php echo strtoupper($_SESSION['websiteName']); ?></h1>
                                <p class="paragraph-2" id="my-index-paragraph">With over 40 years of experience, we offer a friendly and professional service, so that you can have peace of mind. All work carried out by our qualified mechanics are to the highest standard. Our MOTs are £29 for bikes and £50 for cars. We also offer a free courtesy car, or a free collection and delivery service.</p>
                                <a href="#" id="my-book-mot-link">Book your MOT today!</a>
                            </div>
                        </div>

                        <div class="col-sm" id="index-image">
                            <img style="height: 90%" id="ind-img" src="images/login-image.jpg" width="100%">
                        </div>

                    </div>
                </div>
                <footer class="page-footer font-small blue pt-4" id="my-footer">

                    <!-- Footer Links -->
                    <div class="container-fluid text-center text-md-left" id="my-footer-div">

                        <!-- Grid row -->
                        <div class="row">

                            <!-- Grid column -->
                            <div class="col-md-6 mt-md-0 mt-3">

                                <!-- Content -->
                                <h5 class="text-uppercase"><b>GARAGE</b></h5>
                                <!--<p>Here you can use rows and columns to organize your footer content.</p>-->
                                <a href="#" id="footer-img"><img src="images/spanner-logo.png" width="70px" height="70px"></a>


                            </div>
                            <!-- Grid column -->

                            <hr class="clearfix w-100 d-md-none pb-3">

                            <!-- Grid column -->
                            <div class="col-md-3 mb-md-0 mb-3">

                                <!-- Links -->


                            </div>
                            <!-- Grid column -->

                            <!-- Grid column -->
                            <div class="col-md-3 mb-md-0 mb-3">

                                <!-- Links -->
                                <h5 class="text-uppercase">Links</h5>

                                <ul class="list-unstyled">
                                    <li>
                                        <a href="#">Book an MOT</a>
                                    </li>
                                    <li>
                                        <a href="#">Contact</a>
                                    </li>
                                    <li>
                                        <a href="#">Login/Register</a>
                                    </li>
                                    <li>
                                        <a href="#">Index</a>
                                    </li>
                                </ul>

                            </div>
                            <!-- Grid column -->

                        </div>
                        <!-- Grid row -->

                        <div class="footer-copyright py-3">Website created using
                            <a href="https://www.linkedin.com/in/matthew-fard-772393200/" target="_blank" class="link-3">Matthew Fard's</a>
                            website creation tool
                        </div>

                    </div>
                    <!-- Footer Links -->

                    <!-- Copyright -->

                    <!-- Copyright -->

                </footer>
            </div>
        </div>

<section id="customiser" style="max-width: 1000px; margin: auto">
    </div>
        <div class="container px-4 px-lg-5">

        <div class="row gx-4 gx-lg-5 justify-content-center mb-5">
            <form id="contactForm" method="post" action="complete.php">
                <!-- Images Picker -->
                <div class="form-floating mb-3" style="margin-top: 40px">
                    <div class="form-group" id="my-left-form-box2" style="width: 33%; float: left">
                        <p id="my-navlink2" onclick="showLogos()"><i class="fa fa-pencil"></i> Change Logo</p>
                        <input type="file" id="image_input1" name="fileToUpload1" accept="image/*" style="display: none">
                        <input type="hidden" name='hidden-logo' id="hidden-logo" value="spanner-logo.png">
                    </div>
                    <div class="form-group" id="my-right-form-box2" style="width: 33%; float: left">
                        <p id="my-navlink3" onclick="showImages()"><i class="fa fa-pencil"></i> Change Main Image</p>
                        <input type="file" id="image_input" name="fileToUpload" accept="image/*" style="display: none">
                        <input type="hidden" name="hidden-image" id="hidden-image" value="login-image.jpg">
                    </div>
                    <div class="form-group" id="my-right-form-box2" style="width: 33%; float: left">
                        <p id="my-navlink3" onclick="showLayouts()"><i class="fa fa-pencil"></i> Change Layout</p>
                        <input type="file" id="image_input" name="fileToUpload" accept="image/*" style="display: none">
                    </div>
                    <!-- Logo tiles -->
                    <div class="form-group" id="change-logo">
                        <div class="wall" id="tileContainer" style="display: none; max-width: 65%">

                            <label class="brick tile-picker" onclick="changeLogo('wheel')" id="logo-select"  style="background-image: url('images/wheel-logo.png')">
                                <input type="checkbox">
                                <i class="tile-checked"></i>
                            </label>
                            <label class="brick tile-picker" id="logo-select" onclick="changeLogo('spanner')" style="background-image: url('images/spanner-logo.png')">
                                <input type="checkbox" checked>
                                <i class="tile-checked"></i>
                            </label>
                            <label class="brick tile-picker" id="logo-select" onclick="changeLogo('car')" style="background-image: url('images/car-logo.png')">
                                <input type="checkbox">
                                <i class="tile-checked"></i>
                            </label>
                            <label class="brick tile-picker">
                                <input type="checkbox">
                                <i class="tile-checked"></i>
                            </label>
                            <label class="brick tile-picker">
                                <input type="checkbox">
                                <i class="tile-checked"></i>
                            </label>
                            <label class="brick tile-picker">
                                <input type="checkbox">
                                <i class="tile-checked"></i>
                            </label>
                            <label class="brick tile-picker">
                                <input type="checkbox">
                                <i class="tile-checked"></i>
                            </label>
                            <label class="brick tile-picker">
                                <input type="checkbox">
                                <i class="tile-checked"></i>
                            </label>
                            <label class="brick tile-picker">
                                <input type="checkbox">
                                <i class="tile-checked"></i>
                            </label>
                            <label class="brick tile-picker">
                                <input type="checkbox">
                                <i class="tile-checked"></i>
                            </label>
                            <label class="brick tile-picker">
                                <input type="checkbox">
                                <i class="tile-checked"></i>
                            </label>
                            <label class="brick tile-picker" for="image_input1" id="logo-select" style="background-image: url('images/upload-logo.png')">

                                <input type="checkbox">
                                <i class="tile-checked"></i>
                            </label>
                        </div>
                    </div>
                    <!-- Image tiles -->
                    <div class="form-group" id="change-image">
                        <div class="wall" id="tileContainer-img" style="display: none; max-width: 100%; float: right">

                            <label class="brick2 tile-picker" id="image-select" onclick="changeImage('garage')" style="background-image: url('images/garage-image.jpg')">
                                <input type="checkbox" class="myCheckboxes">
                                <i class="tile-checked"></i>
                            </label>
                            <label class="brick2 tile-picker" id="image-select" onclick="changeImage('login')" style="background-image: url('images/login-image.jpg')">
                                <input type="checkbox" class="myCheckboxes" checked>
                                <i class="tile-checked"></i>
                            </label>
                            <label class="brick2 tile-picker" id="image-select" onclick="changeImage('spanner')" style="background-image: url('images/spanner-image.jpg')">
                                <input type="checkbox" class="myCheckboxes">
                                <i class="tile-checked"></i>
                            </label>
                            <label class="brick3 tile-picker" id="image-select2" onclick="changeImage('portrait')" style="background-image: url('images/portrait-image.jpg'); display: none">
                                <input type="checkbox" class="myCheckboxes">
                                <i class="tile-checked"></i>
                            </label>
                            <label class="brick3 tile-picker" id="image-select2" onclick="changeImage('landscape')" style="background-image: url('images/landscape-image.jpg'); display: none">
                                <input type="checkbox" class="myCheckboxes">
                                <i class="tile-checked"></i>
                            </label>
                            <label class="brick2 tile-picker" id="image-select" onclick="changeImage('car')" style="background-image: url('images/car-image.jpg')">
                                <input type="checkbox" class="myCheckboxes">
                                <i class="tile-checked"></i>
                            </label>
                            <label class="brick2 tile-picker" for="image_input" id="logo-select2" style="background-image: url('images/upload-logo.png')">
                                <input type="checkbox" class="myCheckboxes">
                                <i class="tile-checked"></i>
                            </label>

                        </div>
                    </div>
                    <!-- Layout tiles -->
                    <div class="form-group" id="change-image">
                        <div class="wall" id="tileContainer-layout" style="display: none; max-width: 100%; float: right">

                            <label class="brick4 tile-picker" id="layout-select" onclick="layout1()" style="background-image: url('images/layout1.png')">
                                <input type="checkbox" checked>
                                <i class="tile-checked"></i>
                            </label>
                            <label class="brick4 tile-picker" id="layout-select" onclick="layout2()" style="background-image: url('images/layout2.png')">
                                <input type="checkbox">
                                <i class="tile-checked"></i>
                            </label>
                        </div>
                    </div>
                    </div>

                <!-- Colour picker-->
                <div class="form-floating mb-3">
                    <div class="form-group" id="my-left-form-box2" style="margin-bottom: 40px; margin-top: 50px">
                        <input type="color" id="head" name="primary"
                               value="#000000" style="width: 20%;" onchange="changePrimaryColour(this.value)">
                        <label for="head">Primary Colour</label>
                    </div>
                    <div class="form-group" id="my-right-form-box2" style="margin-bottom: 40px; margin-top: 50px">
                        <input type="color" id="head1" name="secondary"
                               value="#3a3aa4" id="secondary-color" style="width:20%;" onchange="changeSecondaryColour(this.value)">
                        <label for="head1" >Secondary Colour</label>
                    </div>
                </div>
                <!-- Paragraph Writer-->
                <div>
                    <label>In less than 80 words, sell your business to your customers. This text will be on the front page of your website and will give your customers an impression of your garage:</label>
                    <textarea type="text" rows="5" cols="50" class="form-control" oninput="writeText(this.value)" placeholder="Your Text Here..." name="paragraphText" id="my-login-input" maxlength="999" value=""  /></textarea>
                </div>

                <hr class="divider" />

                <!-- Submit success message-->
                <!---->
                <!-- This is what your users will see when the form-->
                <!-- has successfully submitted-->
                <div class="d-none" id="submitSuccessMessage">
                    <div class="text-center mb-3">
                        <div class="fw-bolder">Form submission successful!</div>
                        To activate this form, sign up at
                        <br />
                        <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                    </div>
                </div>
                <!-- Submit error message-->
                <!---->
                <!-- This is what your users will see when there is-->
                <!-- an error submitting the form-->
                <div class="d-none" id="submitErrorMessage" style="border-radius: 15px;"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                <!-- Submit Button-->
                <div class="d-grid"><input style="width: 225px; margin: auto; position: relative" class="btn btn-primary btn-xl" id="submitButton" name="step3" type="submit" value="Next"></div>

            </form>
        </div>
    </div>
</section>



<!--Dynamic Colour Script -->
<script>
    function changeSecondaryColour(colour)
    {
        var link = document.getElementsByClassName("nav-link");
        link[4].style = "color: " + colour;
        link[5].style = "color: " + colour;
        link[6].style = "color: " + colour;

        document.getElementById("my-book-mot-link").style = "background-color: " + colour;
        document.getElementById("my-footer").style = "background-color: " + colour;
    }

    function changePrimaryColour(colour)
    {
        //document.getElementById("my-nav-link").style = "color: " + colour;
        var link = document.getElementsByClassName("nav-link");
        link[7].style = "background-color: " + colour;
        document.getElementById("my-heading").style = "color: " + colour;
    }
</script>

<!-- Show Logos script -->
<script>
    function showLogos()
    {
        if(document.getElementById("tileContainer").style.display == "none")
        {
            document.getElementById("tileContainer").style.display = "block";
            document.getElementById("tileContainer-img").style.display = "none";
            document.getElementById("tileContainer-layout").style.display = "none"
        }
        else {
            document.getElementById("tileContainer").style.display = "none"
        }
    }
</script>

<!-- Show images script -->
<script>
    function showImages()
    {
        if(document.getElementById("tileContainer-img").style.display == "none")
        {
            document.getElementById("tileContainer-img").style.display = "block";
            document.getElementById("tileContainer").style.display = "none"
            document.getElementById("tileContainer-layout").style.display = "none"
        }
        else {
            document.getElementById("tileContainer-img").style.display = "none"
        }
    }

</script>

<!-- Show layouts script -->
<script>
    function showLayouts()
    {
        if(document.getElementById("tileContainer-layout").style.display == "none")
        {
            document.getElementById("tileContainer-layout").style.display = "block";
            document.getElementById("tileContainer").style.display = "none"
            document.getElementById("tileContainer-img").style.display = "none"
        }
        else {
            document.getElementById("tileContainer-layout").style.display = "none"
        }
    }

</script>

<!-- Logo Selector script --->
<script>
    document.addEventListener("DOMContentLoaded", function() {
        const checkboxes = document.querySelectorAll('#tileContainer .tile-picker input[type=checkbox]');

        checkboxes.forEach(function(checkbox) {
            checkbox.addEventListener('change', function() {
                if (this.checked) {
                    checkboxes.forEach(function(innerCheckbox) {
                        if (innerCheckbox !== checkbox) {
                            innerCheckbox.checked = false;
                        }
                    });
                }
            });
        });
    });
</script>

<!-- Image Selector script --->
<script>
    document.addEventListener("DOMContentLoaded", function() {
        const checkboxes = document.querySelectorAll('#tileContainer-img .tile-picker input[type=checkbox]');

        checkboxes.forEach(function(checkbox) {
            checkbox.addEventListener('change', function() {
                if (this.checked) {
                    checkboxes.forEach(function(innerCheckbox) {
                        if (innerCheckbox !== checkbox) {
                            innerCheckbox.checked = false;
                        }
                    });
                }

            });
        });
    });
</script>

<!-- Layout Selector script --->
<script>
    document.addEventListener("DOMContentLoaded", function() {
        const checkboxes = document.querySelectorAll('#tileContainer-layout .tile-picker input[type=checkbox]');

        checkboxes.forEach(function(checkbox) {
            checkbox.addEventListener('change', function() {
                if (this.checked) {
                    checkboxes.forEach(function(innerCheckbox) {
                        if (innerCheckbox !== checkbox) {
                            innerCheckbox.checked = false;
                        }
                    });
                }
            });
        });
    });
</script>

<!-- Layout A Changer -->
<script>
    function layout1() {
        // Revert the image source for 'index-image'
        document.getElementById('ind-img').src = "images/login-image.jpg";
        document.getElementById('ind-img').removeAttribute("style"); // Remove custom styles

        // Toggle display of the image tiles inside the 'tileContainer-img'
        let imageTiles = document.querySelectorAll('#tileContainer-img .tile-picker');
        for (let tile of imageTiles) {
            if (window.getComputedStyle(tile).display === "none") {
                tile.style.display = "";
            } else {
                tile.style.display = "none";
            }
        }

        // Revert the value of the 'hidden-image' input
        document.getElementById('hidden-image').value = "login-image.jpg";

        // Move the paragraph back to its original position
        let indexLeft = document.getElementById('index-left');
        let paragraph = document.getElementById('my-index-paragraph');
        let bookMotLink = document.getElementById('my-book-mot-link');

        indexLeft.insertBefore(paragraph, bookMotLink); // Insert the paragraph right after the 'book your MOT today' link
    }

</script>

<!-- Layout B Changer -->
<script>
    function layout2() {
        // Update the image source for the 'index-image'
        document.getElementById('ind-img').src = "images/portrait-image.jpg";
        document.getElementById('ind-img').style = "margin-top: 60px;";

        // Toggle visibility of the image tiles
        let tiles = document.querySelectorAll('.tile-picker');

        for (let tile of tiles) {
            if (window.getComputedStyle(tile).display === "none") {
                tile.style.display = "inline-block"; // or "block", depending on your layout requirements
            } else {
                tile.style.display = "none";
            }
        }

        // Update the value of the 'hidden-image' input
        document.getElementById('hidden-image').value = "portrait-image.jpg";

        // Re-arrange the inner HTML of the 'hint-row' based on the changes you mentioned.
        let hintRow = document.getElementById('hint-row');
        let indexLeft = document.getElementById('index-left');
        let paragraph = document.getElementById('my-index-paragraph');

        // Remove paragraph from index-left
        indexLeft.removeChild(paragraph);

        // Append paragraph after the 'index-image' div
        hintRow.appendChild(paragraph);

        paragraph.style = "margin-top: 70px;"

        // Toggle display of the image tiles inside the 'tileContainer-img'
        let imageTiles = document.querySelectorAll('#tileContainer-img .tile-picker');
        for (let tile of imageTiles) {
            if (window.getComputedStyle(tile).display === "none") {
                tile.style.display = "";
            } else {
                tile.style.display = "none";
            }
        }

    }

</script>

<!-- Logo changing Script -->
<script>
    function changeLogo(image) {

        var garageName = document.getElementById('my-brand').innerText;
        document.getElementById('my-brand').innerHTML = '<img src="images/' + image +'-logo.png" width="95" height="" alt="logo" style="margin-top: -12px; padding-right: 12px"><label class="logo-text-display">'+ garageName +'</label>'
        document.getElementById('footer-img').innerHTML = '<img src="images/' + image +'-logo.png" width="90px" height="70px">'
        document.getElementById('my-navlink2').innerHTML = '<i class="fa fa-pencil"></i> Change (' + image +' logo &#x2705;)'
        document.getElementById('hidden-logo').value = image + '-logo.png'

    }
</script>

<!-- Image changing Script -->
<script>

    function changeImage(image) {

        var garageName = document.getElementById('my-brand').innerText;
        document.getElementById('index-image').innerHTML = '<img id="ind-img" src="images/' + image +'-image.jpg" width="100%" height="90%">'
        document.getElementById('my-navlink3').innerHTML = '<i class="fa fa-pencil"></i> Change (' + image +' image &#x2705;)'
        document.getElementById('hidden-image').value = image + '-image.jpg'

    }

</script>

<!-- Upload Image Script -->
<script>
    const image_input = document.querySelector("#image_input");
    image_input.addEventListener("change", function() {
        const reader = new FileReader();
        reader.addEventListener("load", () => {
            const uploaded_image = reader.result;
            var garageName = document.getElementById('my-brand').innerText;
            document.getElementById('index-image').innerHTML = `<img id="ind-img" src=${uploaded_image} width="100%" height="90%">`
            document.getElementById('my-navlink3').innerHTML = '<i class="fa fa-pencil"></i> Change (custom image &#x2705;)'
            var img = document.getElementById('image_input').value;
            var imgSub = img.substring(12, img.length);
            document.getElementById('hidden-image').value = imgSub;
        });
        reader.readAsDataURL(this.files[0]);
    });
</script>

<!-- Upload Logo Script -->
<script>
    const image_input1 = document.querySelector("#image_input1");
    image_input1.addEventListener("change", function() {
        const reader = new FileReader();
        reader.addEventListener("load", () => {
            const uploaded_image = reader.result;
            var garageName = document.getElementById('my-brand').innerText;
            document.getElementById('my-brand').innerHTML = `</label><img src=${uploaded_image} width="55" height="" alt="logo" style="margin-top: -12px; padding-right: 12px"><label class="logo-text-display">`+ garageName
            document.getElementById('footer-img').innerHTML = `<img src=${uploaded_image} width="70px" height="70px">`
            document.getElementById('my-navlink2').innerHTML = '<i class="fa fa-pencil"></i> Change (custom Image &#x2705;)'
            var img = document.getElementById('image_input1').value;
            var imgSub = img.substring(12, img.length);
            document.getElementById('hidden-logo').value = imgSub;
        });
        reader.readAsDataURL(this.files[0]);
    });
</script>

<!-- Paragraph change Script -->
<script>
    function writeText(txt) {
        document.getElementById("my-index-paragraph").innerText = txt
    }
</script>

<!-- Footer-->

<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- SimpleLightbox plugin JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
<!-- Core theme JS-->
<script src="js/scripts.js"></script>
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<!-- * *                               SB Forms JS                               * *-->
<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>


</body>


<?php require('template/footer.phtml') ?>
